version: 2
updates:
  # Update dependencies for pnpm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'pnpm-dependencies'
      - 'dependabot-auto-merge'
    groups:
      all:
        patterns:
          - '*'
          # No more tailwind fiasco
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Update GitHub Actions workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'ci-dependencies'
      - 'dependabot-auto-merge'
