services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4173:5173'
    environment:
      - GITHUB_TOKEN=""
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Prevents overwriting node_modules
    command: ['pnpm', 'run', 'dev', '--host', '0.0.0.0']
