# syntax=docker/dockerfile:1

ARG NODE_VERSION=20-alpine
ARG PNPM_VERSION=9.14.4

################################################################################
# Base Image
FROM node:${NODE_VERSION} AS base

# Install required dependencies
RUN apk add --no-cache \
    curl \
    jq \
    bash \
    git \
    dcron \
    && corepack enable \
    && corepack prepare pnpm@${PNPM_VERSION} --activate \
    && mkdir -p /usr/src/app

# Set working directory
WORKDIR /usr/src/app

# Install dependencies (this prevents re-installation on every container restart)
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Expose the port for development
EXPOSE 4173

# Command to start the development server
CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"]
