name: Build and Push Docker Image on Add/Remove

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PUB_TOKEN }}

      - name: Generate semantic version
        id: semver
        run: |
          RUN_NUMBER=${GITHUB_RUN_NUMBER}
          MAJOR=$((RUN_NUMBER / 100))
          MINOR=$(((RUN_NUMBER % 100) / 10))
          PATCH=$((RUN_NUMBER % 10))
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Calculated version: $VERSION (from run #$RUN_NUMBER)"

      - name: Set lowercase repo name
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: |
            ${{ env.REPO_LC }}:latest
            ${{ env.REPO_LC }}:${{ env.VERSION }}
            ${{ env.REPO_LC }}:${{ env.VERSION }}-${{ github.sha }}
          platforms: ${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Clean up unused Docker images
        run: |
          if [ ${{ github.event_name != 'pull_request' }} ]; then
            docker image prune -af
          fi
